### ISSUE TITLE
Environment URL points to http:// even when SSL is configured; wait_on_ssl not currently used?

### ISSUE THREAD

**Issue by gbradley** [mehrancodes/laravel-harbor#96]
When creating a site with `FORGE_SSL_REQUIRED` set to true, the comment added to GitHub contains the environment variable using the `http` protocol rather than `https`.

At first I assumed this is due to the ForgeServce's `getSiteLink()` method being called on the newly created site, which will have `isSecured` as false until the LetsEncrypt process completes. According to the docs, [FORGE_WAIT_ON_SSL](https://laravel-harbor.com/docs/configuration/#forge-wait-on-ssl) defaults to true; I can see it being used to set the `wait_on_ssl` config variable, but that doesn't seem to be used anywhere?

Happy to try a PR but would be good to know if `wait_on_ssl` was intended to be usable or not.

**Comment by mehrancodes** [comment]
We are assigning the env keys to CamelCase properties after validation is done [here](https://github.com/mehrancodes/laravel-harbor/blob/c62fcfbccac019ec8b7966e296f36f960b131591/app/Services/Forge/ForgeSetting.php#L203), and [using waitOnSsl property here](https://github.com/mehrancodes/laravel-harbor/blob/c62fcfbccac019ec8b7966e296f36f960b131591/app/Services/Forge/Pipeline/ObtainLetsEncryptCertification.php#L38) to tell Forge wait on SSL. Forge is expected to wait on SSL certification when `wait_on_ssl` is set to True.

However I appreciate any help on debugging the Forge's `isSecured` property.

I think we also should be fine to set `https` on getSiteLink if the `sslRequired()` is True (since some projects may need to skip waiting on certification), ensuring to throw an exception if we got error on certification. What do you think?

**Comment by gbradley** [comment]
Ah I see. Could it just be that the site object isn’t refreshed after being created?

Rather than fetching the site data again, I’d say it’s safe to assume an HTTPS url if the user has requested it (since an exception will be thrown if SSL fails).

**Comment by mehrancodes** [comment]
Agreed! It's fine to do so after the certification is done either by re-fetching the site and assigning it back to `ForgeService->site` or by changing `ForgeSetting->site->isSecured` value. both works well IMO
